### PR TITLE
npm install

### PR DESCRIPTION
**Pull request by SCAuFish**

### CODE REVIEW

**Comment by SCAuFish** [comment]
backend function for token generation.

**Review by yil578 — COMMENTED** [review]
Thanks Cheng this is great 😀. I've seen your generate token code (hardcoded key so far as u said) in Index.js. And package-lock.json can be deleted and re-rerun to solve conflicts between master and your branch. Also, will this repo for firebase functions and module be merged into our main project repo later?

**Comment by SCAuFish** [comment]
@yil578 I would say to keep them in separate repo? Because they technically are separate Apps and follow different deploy procedures.

**Comment by yil578** [comment]
make sense sure.

**Pull request merged**
